sudo: required
language: java
jdk:
  - oraclejdk8
go:
  - "1.20"
go_import_path: github.com/2dust/AndroidLibV2rayLite
git:
  depth: 5
before_script:
  - jdk_switcher use openjdk8
script:
  - java -version
#   - sudo ntpdate -u time.google.com
#   - date
#   - make all
#   - make downloadGoMobile
# script:
#   - make BuildMobile
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file:
    - libv2ray.aar
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
